### ISSUE TITLE
Dynamo/issues/6475

### ISSUE THREAD

**Issue by jonathanroy8676** [LukeyJohnson/BakeryForDynamo#2]
I hope its ok to post here... I'm new at this!
See Issue on Dynamo Hub: https://github.com/DynamoDS/Dynamo/issues/6475

**Comment by LukeyJohnson** [comment]
Ok thanks see my reply https://github.com/DynamoDS/Dynamo/issues/6475#issuecomment-212644940

**Comment by LukeyJohnson** [comment]
closed
