### ISSUE TITLE
Revit Section View at Line

### ISSUE THREAD

**Issue by NickCulley** [LukeyJohnson/BakeryForDynamo#5]
Luke

Further to my comments on Dynamo Nodes I managed to put something together which would allow a list of view heights.

[Section From Line V2.zip](https://github.com/LukeyJohnson/BakeryForDynamo/files/1576231/Section.From.Line.V2.zip)

Not a custom node, just the complete Workspace.

Regards

Nick

**Comment by LukeyJohnson** [comment]
Thanks Nick, I have added that the dyn folder on this repo as well.
